### ISSUE TITLE
Restart doesn't work

### ISSUE THREAD

**Issue by tinywrkb** [flathub/com.google.Chrome#1]
`chrome://restart` generates the following error `bwrap: execvp /app/bin/../lib/zypak-helper: No such file or directory`.  
I'm doing nothing special, just running Chrome 84.0.4147.105 with a new and empty profile, no Chrome flags or extensions.

**Comment by refi64** [comment]
Should be fixed now, turns out I was looking for the helper binary in the wrong place...

**Comment by tinywrkb** [comment]
It works great now ;)
