### ISSUE TITLE
Failing install due to missing runtime org.freedesktop.Platform/x86_64/21.08

### ISSUE THREAD

**Issue by EmperorKonstantin** [flathub/com.google.Chrome#103]
```zsh
➜  ~ flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo

➜  ~ flatpak install com.google.Chrome

Looking for matches…
Found similar ref(s) for ‘com.google.Chrome’ in remote ‘flathub-beta’ (system).
Use this remote? [Y/n]: Y
error: The application com.google.Chrome/x86_64/beta requires the runtime org.freedesktop.Platform/x86_64/21.08 which was not found
```

**Comment by wjt** [comment]
Do you have the non-beta Flathub repo configured? (You need it.)

**Comment by EmperorKonstantin** [comment]
I have it configured. 

![image](https://user-images.githubusercontent.com/3018990/149034552-61e49cc9-0823-4475-b2d3-14f44cff23c0.png)

![image](https://user-images.githubusercontent.com/3018990/149034837-40c7f510-16be-4bec-87d7-893e74c8a337.png)

**Comment by wjt** [comment]
Please copy and paste the full output of `flatpak remotes -d`.

**Comment by Programmerino** [comment]
I have the same issue and my command output is:
```
Name         Title        URL                               Collection ID Subset Filter Priority Options … … Homepage             Icon
flathub-beta Flathub beta https://dl.flathub.org/beta-repo/ -             -      -      1        system  … … https://flathub.org/ https://dl.flathub.org/repo/logo.svg
flathub      Flathub      https://dl.flathub.org/repo/      -             -      -      1        user    … … https://flathub.org/ https://dl.flathub.org/repo/logo.svg
```

**Comment by Programmerino** [comment]
This is likely an instance of https://github.com/flatpak/flatpak/issues/4724#issuecomment-1030512949.

The solution is `sudo flatpak remote-delete flathub-beta; flatpak remote-add --user flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo` in my configuration

**Comment by EmperorKonstantin** [comment]
This worked to install Chrome, we should update the readme.md.

**Comment by refi64** [comment]
this will be on stable at some point soon anyway, just going to close for now
