### ISSUE TITLE
hoow to Google Chrome from Flathub-beta to Flathub?

### ISSUE THREAD

**Issue by candrapersada** [flathub/com.google.Chrome#124]
how to change Flathub-beta to Flathub?
![gambar](https://user-images.githubusercontent.com/36833664/161401668-05222073-e201-4a26-8e92-9469d75ee719.png)

**Comment by refi64** [comment]
You can just `flatpak install com.google.Chrome//stable` and `flatpak remove com.google.Chrome//beta`; Flatpak won't remove any user data by default.
