### ISSUE TITLE
Arm version fails to start

### ISSUE THREAD

**Issue by waddon1** [flathub/com.google.Chrome#128]
When starting the Chrome flatpak on Aarch64 it fails to start with the error:
Failed to fill defaults: Failed to infer sandbox filename: Could not locate sandbox file (looked for '/app/extra/chrome-sandbox', '/app/extra/chrome-dev-sandbox', and '/app/extra/chrome-sandbox')

**Comment by tinywrkb** [comment]
> Arm version

This would have been nice if it was correct. ;)

> When starting the Chrome flatpak on Aarch64 it fails to start with the error:
Failed to fill defaults: Failed to infer sandbox filename: Could not locate sandbox file (looked for '/app/extra/chrome-sandbox', '/app/extra/chrome-dev-sandbox', and '/app/extra/chrome-sandbox')

Do you mean with qemu-user? This seems like an issue with Zypak, but suspect it's not the only problem.  
Try running Chrome directly and without a sandbox like this
```
$ flatpak run --command=/app/extra/chrome com.google.Chrome --no-sandbox
```
I suspect that this won't end well. If so, then you can try adding `--single-process`.  
I've hit the same issue when trying to run aarch64 Electron apps, and it doesn't look promising.

**Comment by refi64** [comment]
[Chromium](https://flathub.org/apps/details/org.chromium.Chromium) is available for arm64 (I actively used it), so that would be your best bet.
