### ISSUE TITLE
flatpak override provides CUPS access but printing does not work

### ISSUE THREAD

**Issue by oxwivi** [flathub/com.google.Chrome#13]
I've used Flatseal to give access to CUPS to the Chrome Flatpak, and Chrome's printing UI does show my printers; however, going ahead with printing does not do anything, print queue on the host shows nothing.

In addition, _Print using system dialog..._ does not show any of the printers, unlike the "native" Chrome UI.

**Comment by refi64** [comment]
@oxwivi please try the latest version once the [build](https://flathub.org/builds/#/builders/32/builds/28347) is complete & published, this should be fixed now

**Comment by oxwivi** [comment]
Thank you! Working perfectly.
