### ISSUE TITLE
Enable force dark mode

### ISSUE THREAD

**Issue by SandHilt** [flathub/com.google.Chrome#131]
In Google Chrome, i can pass some flags like --force-dark-mode when chrome can "read" color from system.
Please, allow pass some flags to chrome.

**Comment by rayfoss** [comment]
This is really bad in OLED laptops as the white border under XFCE is intolerable. PWAs have no way to get around the white border, non of the themes affect the flatpak.
![Screenshot_2022-05-12_15-55-35](https://user-images.githubusercontent.com/876076/168166678-3de9fac5-913c-41d9-b5cb-a5b58f9d684e.png)

**Comment by refi64** [comment]
You can place them in `~/.var/app/com.google.Chrome/config/chrome-flags.conf`.
