### ISSUE TITLE
Cannot share screen on Wayland

### ISSUE THREAD

**Issue by yajo** [flathub/com.google.Chrome#143]
When I'm on a meeting in meet.google.com and I share screen with this app, it only shares a black screen.

**Comment by tinywrkb** [comment]
Lazy bug reporting. What distro and desktop environment and version are you using? For best screencasting experience, use the latest Gnome desktop release (it doesn't mean I like Gnome or recommend it, it's just doing better in this case).

**Comment by yajo** [comment]
I use gnome 41 in fedora 36.

I think I finally got it working after enabling the pipewire flags. I'll reopen otherwise. 

Maybe that could be advertised somewhere. 

Thanks!
