### ISSUE TITLE
Picture in picture not working

### ISSUE THREAD

**Issue by blutch112** [flathub/com.google.Chrome#147]
Hello,
Picture in picture does not work properly. The pip window is not always on top.
I'm on GNOME 42.

Cordially

**Comment by tinywrkb** [comment]
Should work in X/XWayland, but [there's no PiP support in Wayland](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/44).

**Comment by douglasilvadev** [comment]
An alternative way to use this feature is through extensions. Just install from the store to resolve for now: 

https://chrome.google.com/webstore/detail/picture-in-picture-extens/hkgfoiooedgoejojocmhlaklaeopbecg

**Comment by refi64** [comment]
This is a Wayland thing, try [using this GNOME extension](https://extensions.gnome.org/extension/4691/pip-on-top/).
