### ISSUE TITLE
Add dev branch

### ISSUE THREAD

**Issue by rajveermalviya** [flathub/com.google.Chrome#15]
is it possible to add chrome-dev (google-chrome-unstable) builds too?

i wanted to test out ozone-wayland in chrome-dev, tried it using this repo by changing some urls and after some renaming (**flatpak** is amazing!!) it worked!!

is it possible to add another branch (like dev) and use _flathub_ directly?

**Comment by refi64** [comment]
This could be done later on, I guess once Chrome hits stable, but right now
we're still working out kinks and I don't really have the bandwidth to
manage pulling fixes across multiple Flatpaks.

**Comment by evenreven** [comment]
Now that this flatpak build is updated to Chrome 87, running it on Wayland is as simple as `flatpak run --socket=wayland com.google.Chrome --enable-features=UseOzonePlatform --ozone-platform=wayland`. Works really well so far! It respects experimental Wayland fractional scaling and everything.

It's probably too early to make this the default somehow? I don't know anything about flatpak packaging, so excuse my ignorance. In the meantime I'll just modify the desktop file. :)

**Comment by refi64** [comment]
Definitely a bit too early, we're likely not going to enable it until it's enabled upstream. You can view full current list of Ozone Wayland bugs [here](https://bugs.chromium.org/p/chromium/issues/list?q=Proj%3DOzone-Wayland&can=2), and the main blockers are all mentioned [here](https://bugs.chromium.org/p/chromium/issues/detail?id=578890).

Note that you don't have to actually modify the desktop file, you can just save the new flags, one per line, to `~/.var/app/com.google.Chrome/config/chrome-flags.conf`.

**Comment by tinywrkb** [comment]
@refi64 One issue that is not mentioned is IME frameworks compatibility. I'm not sure about IBus but the last time I tried Ozone Wayland didn't work with Fcitx and this is not mentioned in the [IME meta bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1022724).  
So I suggest adding this to a preconditions list before shipping so you won't break input for Asian users.

With Ozone X11 it does work so if shipping Ozone early then it might be a good idea to default to X11 platform.

**Comment by refi64** [comment]
Oof that's not great, yeah the only way I personally forsee us shipping enabling Wayland early is if the *only* reason it's not flipped on upstream is something related to distribution that doesn't apply to Flatpaks.

**Comment by refi64** [comment]
Chrome unstable is on Flathub now.
