### ISSUE TITLE
Wayland with mixed DPI monitor setup not working correctly for Chrome

### ISSUE THREAD

**Issue by hzulla** [flathub/com.google.Chrome#154]
Please see https://github.com/flatpak/flatpak/issues/5033 for details.

If you run the flatpak version of Chrome on Ubuntu/Wayland and have two monitors attached with different scaling, the Chrome UI will not change its scaling when moved from the hidpi monitor to the lodpi monitor and back.

The workaround `--nosocket=fallback-x11 --nosocket=x11 --socket=wayland` mentioned on https://github.com/flatpak/flatpak/issues/5033 works for Wayland-aware applications like Firefox, but not for flatpak Chrome.

**Comment by refi64** [comment]
Does this work with non-Flatpak Chrome? It doesn't entirely sound like something that can be fixed on this end...

**Comment by hzulla** [comment]
Ok, just tested this. Indeed, Wayland isn't used by default in the upstream package, one has to change `chrome://flags/#ozone-platform-hint` to `auto` and then things work with flatpak as well as with deb.
