### ISSUE TITLE
Version 105.0.5195.102 isn't on Flathub?

### ISSUE THREAD

**Issue by tv42** [flathub/com.google.Chrome#156]
Hi. I'm a Flathub/Flatpak newbie, apologies if I'm confused.

https://flathub.org/apps/details/com.google.Chrome still says 105.0.5195.52-1, and flatpak only installs .52, not .102.

I see commit 0cd4b8d4938c76622ecc42428c7fa5b2516c6d0d merged in master 4 days ago, so by my understanding Flathub should have 105.0.5195.102 already.

Maybe something needs to be nudged to make the new version be available on Flathub?

It seems there was a temporary build error somewhere along the line (builder couldn't reach github.com), maybe that confused the automation?

**Comment by refi64** [comment]
Ack yeah the build failed, rebuilt so it should be up now.
