### ISSUE TITLE
Cannot follow the dark theme of KDE

### ISSUE THREAD

**Issue by dandidwi** [flathub/com.google.Chrome#160]
Chrome version of Flatpak cannot follow the dark theme of KDE Plasma, but in the official version you can.Distro that I use Kubuntu 22

**Comment by sabbir2world** [comment]
I can also confirm that Flatpak Chrome isn't following system theme as @dandidwi mentioned above. I'm using KDE Neon user edition. Flatpak firefox working just fine so I think it's something to do with Chrome itself.

**Comment by Etaash-mathamsetty** [comment]
chrome doesn't support this on linux even without flatpak :/
it's another reason to use firefox unfortunately

**Comment by tinywrkb** [comment]
That's an [upstream issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1340411), not Flatpak-specific.

**Comment by Danik1601** [comment]
> That's an [upstream issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1340411), not Flatpak-specific.

Please star the linked issue to add a vote

**Comment by tunix** [comment]
ChromeDev is available as flatpak and it's on version 114 -- however it doesn't honor my theme preference when I change GNOME theme to dark mode. 😞

**Comment by Danik1601** [comment]
> ChromeDev is available as flatpak and it's on version 114 -- however it doesn't honor my theme preference when I change GNOME theme to dark mode. 😞

Someone (presumably on version 114) [reported](https://bugs.chromium.org/p/chromium/issues/detail?id=998903#c137) that it is working. Maybe it has landed in Canary but not in Dev yet

**Comment by Danik1601** [comment]
By the way, @tunix, you have to be on [GNOME version 42](https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/) ([KDE Plasma version 5.24](https://kde.org/announcements/plasma/5/5.24.0/#:~:text=Speaking%20of%20colors,Latte%20Dock.)) or newer for this feature to work since it uses standardized FreeDesktop light/dark color scheme preference.

**Comment by tunix** [comment]
I run GNOME 43 with Fedora Silverblue 37, so that shouldn't be a problem I guess. This feature works fine with Firefox.

**Comment by hferreiro** [comment]
The fix landed in 114.0.5708.0: https://chromiumdash.appspot.com/commit/1acb960204281157ac3a583a07ce07e2754ea42b.
com.googleChromeDev is at 114.0.5696.0: https://github.com/flathub/com.google.ChromeDev/blob/master/com.google.ChromeDev.yaml#L124.

**Comment by mohssineAboutaj** [comment]
same in **GNOME** v43.1

**Comment by Etaash-mathamsetty** [comment]
I downloaded a daily build of chromium and it seems to work really well on it, so hope it comes to the dev channel soon.

**Comment by refi64** [comment]
Fixed upstream, so closing here.
