### ISSUE TITLE
`com.google.Chrome --help` crashes.

### ISSUE THREAD

**Issue by will-ca** [flathub/com.google.Chrome#172]
```bash
$ com.google.Chrome --help
Gtk-Message: 15:57:22.371: Failed to load module "xapp-gtk3-module"
Gtk-Message: 15:57:22.371: Failed to load module "canberra-gtk-module"
[2 zypak-helper] Wait found events, but sd-event found none
[1120/155722.454433:FATAL:chrome_main_delegate.cc(432)] execlp failed: No such file or directory (2)
```

**Comment by akiszka** [comment]
Hi! If this still happens maybe I or someone else could help. It would help us if you provided this information:
1. what OS are you on?
2. how are you starting com.google.Chrome - what shell, what directory?
3. can you send any additional logs ([this thread could be a good start to get them](https://stackoverflow.com/questions/10291076/is-it-possible-to-run-chrome-in-debug-mode))?

**Comment by will-ca** [comment]
Thanks for the offer of assistance. I have not used the Chrome Flatpak in a while. I'm closing this issue as I suppose it will not be actionable unless somebody else also reproduces it.
