### ISSUE TITLE
Doesn't recognize my security key (Yubikey)

### ISSUE THREAD

**Issue by GlenKPeterson** [flathub/com.google.Chrome#182]
Thank you for providing this package!  I'm a huge fan of both Chrome and Flatpak.

I'm using the latest Fedora Silverblue on a 64 bit desktop.  Brand new OS install, then:

```shell
flatpak install flathub com.google.Chrome
flatpak run com.google.Chrome
```

In Chrome, I then try to sign in to my Google account.  It prompts me for my security key.  I insert it into the USB drive and the key flashes once, but doesn't keep flashing like it's supposed to.  When I press it, nothing happens.  Chrome continues to show the waiting-for-security-key dialog.

Maybe this is a security configuration?  I had the same issue installing chrome in a toolbox from the command line.  Pretty sure it works without complaint if I add the chrome repo using `rpm-ostree`.  Let me know if there's a better place to post this question/issue.

**Comment by wjt** [comment]
Does it work if you insert the security key before you start Chrome?

**Comment by wjt** [comment]
https://github.com/flatpak/flatpak/issues/2764 and/or https://github.com/flatpak/xdg-desktop-portal/issues/227

**Comment by GlenKPeterson** [comment]
So, people are working on a solution for this sort of thing for all Flatpaks and security keys.  To be expected with an emerging technology.  I'll follow the progress there.  Thanks for your prompt and spot-on replies!

**Comment by fansari** [comment]
This is an issue I have with Chrome flapak since I use it. I hope this will eventually been solved.
