### ISSUE TITLE
Mouse Cursor isn't obeying system cursor theme after Oct 7th update

### ISSUE THREAD

**Issue by brittyazel** [flathub/com.google.Chrome#19]
As you can see in my screenshot below, Chrome is making use of some 'fallback' mouse cursor after today's update. I am using GNOME 3.38 and up until today Chrome has respected the normal mouse cursor used in GNOME and GTK apps, but today it switched to the one you see below. (It's next to the "Preview" tab header in the screenshot)

Other than the wrong theme, functionality wise it seems to work just fine.

![Screenshot from 2020-10-07 09-04-16](https://user-images.githubusercontent.com/3747347/95357004-28e51200-087c-11eb-914e-b03ada26b726.png)

**Comment by refi64** [comment]
On HiDPI displays, the cursor is actually insanely small as well. Not sure yet if this is an upstream issue, but I'd imagine it would already be reported if it were reproducible outside the sandbox...

**Comment by hferreiro** [comment]
That looks like hand2 at https://tronche.com/gui/x/xlib/appendix/b/. The fallback is used when the cursor cannot be found in the system theme. Can you reproduce that on upstream Chrome? Have you changed your cursor theme settings?

**Comment by MartinBriza** [comment]
It's happenning to me as well in KDE Plasma under Xorg and the cursors are wrong only in Chrome, all other apps (regardless if regular packages or Flatpak) have cursors from my desktop theme (Plasma default - Breeze).

**Comment by hferreiro** [comment]
@refi64 using `$ flatpak enter com.google.Chrome /bin/bash` I noticed that /usr/share/icons only contains a hicolor directory. Adwaita is missing there.

**Comment by brittyazel** [comment]
Did something change with this package to cause the cursor theme to not be present? Maybe the GNOME runtime isn't providing it properly or something. I'm do t know enough about where the cursor theme comes from to speculate where the issue is

**Comment by refi64** [comment]
Pretty sure they've always been in /run/host/share/icons

**Comment by brittyazel** [comment]
Can confirm, that it works. Thanks a bunch!

**Comment by Bonteruel** [comment]
> It's happenning to me as well in KDE Plasma under Xorg and the cursors are wrong only in Chrome, all other apps (regardless if regular packages or Flatpak) have cursors from my desktop theme (Plasma default - Breeze).
Hi. I'm using KDE in Debian with same problem.
SOLUTION: Just do
nano ~/.config/gtk-3.0/settings.ini
and find the line CursorTheme=
set the theme you selected. Then, logout, restart the X or reboot your pc.
Works with FIrefox and Chrome
