### ISSUE TITLE
KDE Plasma Integration extension not working

### ISSUE THREAD

**Issue by DavideDunne** [flathub/com.google.Chrome#194]
Just made a clean install of chrome and installed such extension, getting an error message
Might be because flatpaks are not good in interacting with the desktop environment
![Screenshot_20230301_231428](https://user-images.githubusercontent.com/111002142/222337390-ad95a51c-07e0-4a7b-aff4-6717b645e349.png)

I am using Plasma 5.25.5 btw

**Comment by tinywrkb** [comment]
[I don't believe this is supported yet](https://github.com/flatpak/xdg-desktop-portal/issues/655).
