### ISSUE TITLE
It takes Chrome too much time to open links given by external application due to slow Flatpak session setup

### ISSUE THREAD

**Issue by tinywrkb** [flathub/com.google.Chrome#2]
1. Launch Chrome Flatpak app so we would have a running Chrome session (with accessible Chrome singleton socket).
```
$ com.google.Chrome
```
2. Now simulate a request from an external application to open a link in Chrome
```
$ time com.google.Chrome 'http://google.com`
Opening in existing browser session.

real	0m1.469s
user	0m0.042s
sys	0m0.011s
```
3. Let's do the same with a non-Flatpak Chromium session in install on the host system
```
$ time chromium 'http://google.com'
Opening in existing browser session.

real	0m0.243s
user	0m0.121s
sys	0m0.049s
```

This becomes more apparent when the app making the request introducing its own delay (e.g. Neovim with Markdown plugin).

**Comment by refi64** [comment]
Hmm I can't reproduce this over here, it's at 0.03s for the latter case. Could this somehow be related to the portal crash in #2?

**Comment by tinywrkb** [comment]
I guess so as the flatpak-portal crash happens each time Chrome is started no matter if a Chrome session is already running.  
So I'll close this for now.
