### ISSUE TITLE
Dark Mode not working in version 114.0.5735.133-1

### ISSUE THREAD

**Issue by javierjosev** [flathub/com.google.Chrome#221]
After updating to version 114.0.5735.133-1 dark mode stopped working.

In order to force dark mode, the command I use to run Chrome is:
`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/chrome --file-forwarding com.google.Chrome @@u %U --enable-features=WebUIDarkMode --force-dark-mode @@`
In Chrome, GTK theme is selected. I am using Linux Mint with the "Mint-Y-Dark-Teal" theme.

Downgrading to version 113.0.5672.126-1 solved the problem.
It caught my attention that when I downgraded Chrome, flatpak installed "org.gtk.Gtk3theme.Mint-Y-Aqua" again. I don't know if it has something to do with this problem.

`        ID                                      Branch             Op           Remote           Download
 1. [✓] org.gtk.Gtk3theme.Mint-Y-Aqua           3.22             i            flathub          64,5 kB / 96,6 kB
 2. [✓] com.google.Chrome                       stable           u            flathub          94,7 MB / 6,7 MB`

Thanks!

**Comment by Etaash-mathamsetty** [comment]
if your DE support org.freedesktop's dark mode api, then it should work without any flags. I am not sure if mint supports this though.

**Comment by javierjosev** [comment]
Thanks for your reply @Etaash-mathamsetty. It seems that Cinnamon is a supported DE.
https://www.freedesktop.org/wiki/Desktops/
Any ideas?

**Comment by Etaash-mathamsetty** [comment]
> Thanks for your reply @Etaash-mathamsetty. It seems that Cinnamon is a supported DE. [freedesktop.org/wiki/Desktops](https://www.freedesktop.org/wiki/Desktops/) Any ideas?

That doesn't mean anything, you have to check if org.freedesktop.appearance.color-scheme is supported by mint

**Comment by javierjosev** [comment]
Alright, so let me clarify: for Chrome version 114.0.5735.133-1, it is crucial to have support for "org.freedesktop.appearance.color-scheme" to ensure the dark mode functions correctly. However, is it correct to say that this requirement is not necessary for Chrome version 113.0.5672.126-1? @Etaash-mathamsetty
Thanks!

**Comment by Etaash-mathamsetty** [comment]
> Alright, so let me clarify: for Chrome version 114.0.5735.133-1, it is crucial to have support for "org.freedesktop.appearance.color-scheme" to ensure the dark mode functions correctly. However, is it correct to say that this requirement is not necessary for Chrome version 113.0.5672.126-1? @Etaash-mathamsetty
> Thanks!
> 

Yes
