### ISSUE TITLE
About Page Link Broken

### ISSUE THREAD

**Issue by Shreyas-Ashtamkar** [flathub/com.google.Chrome#24]
The Link which takes us to <a href="https://flathub.org/apps/details/com.google.Chrome">https://flathub.org/apps/details/com.google.Chrome</a> is broken.

![image](https://user-images.githubusercontent.com/51398602/97795244-dbb15180-1c29-11eb-9c53-1d00fbe4a32f.png)

leads to 

![image](https://user-images.githubusercontent.com/51398602/97795261-0e5b4a00-1c2a-11eb-959d-239a9a7e21d1.png)

**Comment by bilelmoussaoui** [comment]
That's an automatically added url. The application is on flathub-beta only for now & it's not supported by the frontend. One day that url would work.
