### ISSUE TITLE
Cannot install on Armbian/Ubuntu Jammy Jellfish on aarch64?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [flathub/com.google.Chrome#245]
Cannot install on Armbian/Ubuntu Jammy Jellfish on aarch64?

$ flatpak install flathub com.google.Chrome
Looking for matches…
error: Nothing matches com.google.Chrome in remote flathub

PRETTY_NAME="Armbian 23.8.3 jammy"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.armbian.com"
SUPPORT_URL="https://forum.armbian.com"
BUG_REPORT_URL="https://www.armbian.com/bugs"
PRIVACY_POLICY_URL="https://www.armbian.com"
UBUNTU_CODENAME=jammy
ARMBIAN_PRETTY_NAME="Armbian 23.8.3 jammy"

**Comment by refi64** [comment]
Google doesn't release Chrome binaries for arm64 Linux. You could try Chromium or Brave instead.
