### ISSUE TITLE
Warning: vkCreateInstance: Found no drivers!

### ISSUE THREAD

**Issue by asegarra** [flathub/com.google.Chrome#250]
Getting the following warning, which pops up after a minute to two of running the flatpak. I don't seem to get this from the native package. Don't know what if anything I'm missing due to this but mentions drivers and did not find a prior issue that matches.

```
Nov 09 18:23:00 ares com.google.Chrome.desktop[25955]: Warning: vkCreateInstance: Found no drivers!
Nov 09 18:23:00 ares com.google.Chrome.desktop[25955]: Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
Nov 09 18:23:00 ares com.google.Chrome.desktop[25955]:     at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:88)
Nov 09 18:23:00 ares com.google.Chrome.desktop[25955]:     at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:458)
Nov 09 18:23:00 ares com.google.Chrome.desktop[25955]:     at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:344)
Nov 09 18:23:00 ares com.google.Chrome.desktop[25955]:     at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:266)
Nov 09 18:23:00 ares com.google.Chrome.desktop[25955]:     at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:521)
```

**Comment by violetmage** [comment]
Is there anything actually broken that goes with this warning, or is it random?

**Comment by asegarra** [comment]
I don't think it's random as it shows up consistently and I can't tell if there is anything broken but it's a warning and maybe tied to some functionality ?

**Comment by violetmage** [comment]
Without any specific steps to reproduce or broken functionality, there's really nothing I can do.

**Comment by asegarra** [comment]
I have an RTX 6700 GPU on Fedora 39. I don’t really do anything to reproduce it just launching the app and waiting for the message to appear in the journal. Honestly even if there were something broke I would probably not be able to tie it to this message unless it’s something very obvious.  You’re position is 100% understandable, this bug report was just meant to bring this to the attention of the maintainers in case it meant something important. I went back to the native package after this just in case so I haven’t used the flatpak for an extended period of time. Thank you for taking the time!
