### ISSUE TITLE
Some browser functions do not work with Ozone set to wayland

### ISSUE THREAD

**Issue by solecram** [flathub/com.google.Chrome#283]
Hello, I noticed that some things don't work well when I set Ozone to enabled and set wayland as a parameter. In my particular experience, it happens that I cannot change a block on a kanban board in Trello, for example, but I believe this could happen in other circumstances that I have not tested.

Look:
[Screencast_20240313_114623.webm](https://github.com/flathub/com.google.Chrome/assets/120270031/617c5195-ac7e-441a-bb35-1bc9bcf6eb61)

Flatpak version:
Flatpak 1.15.6

Flatpak app information:
Google - The web browser from Google

  ID: com.google.Chrome
  Ref: app/com.google.Chrome/x86_64/stable
  Arq.: x86_64
  Branch: stable
  Version: 122.0.6261.111-1
  License: LicenseRef-proprietary
  Origin: flathub
  Collection: org.flathub.Stable
  Installation: system
  Installed: 21,2 MB
  Runtime: org.freedesktop.Platform/x86_64/22.08
  Sdk: org.freedesktop.Sdk/x86_64/22.08

  Commit: cdefadf91e744897584a39a7c84f226de198ee0d47e531f7619441e5901cf95f
  Father: c8143f1b03e3b978f02e4ab14d22142e70fb6ba49b089c3e8fd5aa18f3d3f072
 
OS information:
Operating System: Fedora Linux 40
KDE Plasma Version: 6.0.0
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.8.0-0.rc6.49.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-7200U CPU @ 2.50GHz
Memory: 19.4 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620
Manufacturer: Acer
Product Name: Aspire A515-51
System Version: V2.02

**Comment by refi64** [comment]
Unfortunately upstream wayland support is still unstable and breaks from time to time; I don't think anything about that is something we can fix on our end, outside of backporting specific bug fixes.
