### ISSUE TITLE
flatpak installation failes on EndlessOS

### ISSUE THREAD

**Issue by btreut** [flathub/com.google.Chrome#287]
Details about this problem can be found in the [discussion in the Endless Community](https://community.endlessos.com/t/updating-failes/21385). It started with updating, but it occurs also when trying a fresh installation. If additional information is needed, I'll try my best to provide it.

**Comment by wjt** [comment]
Confusingly there are actually two `com.google.Chrome` Flatpaks available on Endless OS and from your screenshots you're using the one from https://github.com/endlessm/eos-google-chrome-app/, not this one.

**Comment by btreut** [comment]
> not this one

ok, thanks for the hint & the solution [there](https://community.endlessos.com/t/updating-and-later-re-installation-failes-google-chrome/21385/11).
