### ISSUE TITLE
CHROME_EXECUTABLE is not set

### ISSUE THREAD

**Issue by ChristianPauly** [flathub/com.google.Chrome#30]
Hey, for Flutter for Web development I need the CHROME_EXECUTABLE to be set but this doesnt seem to be the case with this Flatpak. Any way how I can set it manually?

**Comment by tinywrkb** [comment]
IDK much about Flutter dev but did you try starting Chrome with `$ flatpak run --env=CHROME_EXECUTABLE=/app/bin/chrome.sh com.google.Chrome`?

**Comment by refi64** [comment]
Untested, but you should be able to just set it to
/var/lib/flatpak/exports/bin/com.google.Chrome or
~/.local/share/flatpak/exports/bin/com.google.Chrome (for system vs user
installs)§

**Comment by refi64** [comment]
Not really an issue we have to fix, would be nice if this could magically work somehow though.
