### ISSUE TITLE
When will this be out of beta?

### ISSUE THREAD

**Issue by romulasry** [flathub/com.google.Chrome#34]
At least one person would like to know: https://github.com/flathub/com.microsoft.Edge/issues/13#issuecomment-774788174

**Comment by dtantono** [comment]
I checked the flatpak link is dead and what happened?

**Comment by Erick555** [comment]
Nothing happened just flathub website doesn't show links for `beta` apps but you can install it just fine.

**Comment by dtantono** [comment]
so, the google chrome for flatpak now is for beta channel only?

**Comment by Erick555** [comment]
It was beta only from the beginning. It may be out of beta some day.

**Comment by LeandroStanger** [comment]
@andrunko @refi64 @Wjt @ramcq???

**Comment by refi64** [comment]
I'm pretty sure there's still some bugs with udev that we patch around in Chromium but I haven't gotten around to submitting upstream fixes, that's mostly the remaining concern.

**Comment by rowbawts** [comment]
Any updates?

**Comment by Mershl** [comment]
Moving Chrome from `flathub-beta` to `flathub` will surely lead to a lot more users and feedback. From my experience it's stable, and good enough. Small quirks are fine IMO.

**Comment by rowbawts** [comment]
> Moving Chrome from `flathub-beta` to `flathub` will surely lead to a lot more users and feedback. From my experience it's stable, and good enough. Small quirks are fine IMO.

I also feel that the beta branch being something you have to go out of your way to find seriously hinders adaptability as people don't see familiar programs such as Google Chrome available.

**Comment by olecraaM** [comment]
Any update on the matter? Do you have a prediction or something, if it's still not possible, do you have an explanation for it?

**Comment by bdaase** [comment]
FWIW, this issue is currently blocking the move to stable for both Edge and Brave.

**Comment by candrapersada** [comment]
https://flathub.org/apps/details/com.google.ChromeDev
![image](https://user-images.githubusercontent.com/36833664/159196641-799bfe9d-528c-428b-8d65-0c03e91002ef.png)

**Comment by refi64** [comment]
Chrome is on Flathub stable now.

**Comment by candrapersada** [comment]
hoow to Google Chrome from beta to stable?
