### ISSUE TITLE
PWAs and shortcuts are associated with the main browser window

### ISSUE THREAD

**Issue by ludvigng** [flathub/com.google.Chrome#39]
Hi!

After granting chrome access to ~/.local/share/applications and ~/.local/share/icons, adding shortcuts to PWAs and other websites they are still associated with the launcher to chrome, meaning they are all grouped under the main window:

![Skärmbild från 2021-03-04 11-09-05](https://user-images.githubusercontent.com/50339757/109948029-39d66a00-7cda-11eb-9672-92ca19582a0b.png)

Checking the WM_CLASSes, they seem to be the set correctly compared to the "regular" version of chrome and are the same for both:
Browser: `WM_CLASS(STRING) = "google-chrome", "Google-chrome"`
YouTube PWA: `WM_CLASS(STRING) = "crx_agimnkijcaahngcdmfeangaknmldooml", "Google-chrome"`

Comparing the desktop files, nothing really stands out.
Flatpak:
> #!/usr/bin/env xdg-open
>
>[Desktop Entry]
>Version=1.0
>Terminal=false
>Type=Application
>Name=YouTube
>Exec='flatpak' 'run' '--branch=beta' '--arch=x86_64' '--command=/app/bin/chrome' 'com.google.Chrome' '--profile-directory=Default' '--app-id=agimnkijcaahngcdmfeangaknmldooml'
>Icon=flatpak-com-google-Chrome-chrome-agimnkijcaahngcdmfeangaknmldooml-Default
>StartupWMClass=crx_agimnkijcaahngcdmfeangaknmldooml

Regular chrome:
>#!/usr/bin/env xdg-open
>[Desktop Entry]
>Version=1.0
>Terminal=false
>Type=Application
>Name=YouTube
>Exec=/usr/bin/google-chrome-stable --profile-directory=Default --app-id=agimnkijcaahngcdmfeangaknmldooml
>Icon=chrome-agimnkijcaahngcdmfeangaknmldooml-Default
>StartupWMClass=crx_agimnkijcaahngcdmfeangaknmldooml

The icons also doesn't show up properly in the launcher:
![Skärmbild från 2021-03-04 11-05-59](https://user-images.githubusercontent.com/50339757/109947633-d3514c00-7cd9-11eb-83cd-1667277ffe77.png)

**Comment by ludvigng** [comment]
Investigating closer, StartupWMClass seems to be missing from the main com.google.Chrome.desktop file, compared to the "regular" package:
`StartupWMClass=Google-chrome`

However, adding this to the desktop file doesn't actually fix the problem either way. Icons seem to have fixed themselves during the day somehow though.

**Comment by pedrofleck** [comment]
I have this issue too.

**Comment by ArcaEge** [comment]
Why is this closed? It's still an issue for me, #47 hasn't been merged.
