### ISSUE TITLE
Request for an official Chrome package

### ISSUE THREAD

**Issue by tinywrkb** [flathub/com.google.Chrome#42]
[Reported upstream](https://bugs.chromium.org/p/chromium/issues/detail?id=1185483).

**Comment by Erick555** [comment]
IIRC maintainers contacted upstream about adding official flatpak sandboxing support and the answer was negative.

**Comment by tinywrkb** [comment]
Google needs to pick up the mantle and maintain the whole thing.  
I don't care about the sandboxing code, it's their problem to solve. If Google's employees don't agree on the work done by volunteer developers putting X many hours of work then please do it differently. Google has a deep pocket to swiftly get it done.  

The main point is that if Google publishes binary releases for Linux then it must be offered also as Flatpak.

**Comment by Erick555** [comment]
Google doesn't have any affiliation with flatpak so I don't know from where did you get idea they _must_ offer their software as flatpaks. The problem isn't the code but lack of interest.

**Comment by tinywrkb** [comment]
Sorry, I very much disagree with you. If you claim to support Linux desktop as a platform then you must package also as Flatpak or you're doing a pretty bad job at it.  
They also don't need to support the XDG dirs spec, Wayland, and etc, but these are agreed-upon standards for Linux desktop as a platform.  
If you don't publish Flatpaks then you don't support the Linux desktop, you just support Debian and Red Hat/Fedora.

**Comment by refi64** [comment]
The patches for this already exist in Chromium, but adding and auditing a sandbox is to be fair also a rather large undertaking to the core browser. Worth also nothing that, although I (obviously) support Flatpaks, its use probably isn't widespread enough to be "the" singular packaging system, and Chromium supports versions of Ubuntu/Debian older than what has a reasonably new Flatpak build so the .debs have to be maintained anyway.

Either way, there's nothing for us to do here.
