### ISSUE TITLE
flatpak_policy.json causes Chrome to be managed

### ISSUE THREAD

**Issue by ludvigng** [flathub/com.google.Chrome#43]
This is by design of course, but it doesn't actually seem to make a difference.

The browser is currently set in managed mode because of the file, giving the user a warning about the browser being managed, which might raise a few eyebrows. This is because the policy file to set `"DefaultBrowserSettingEnabled": false`

This doesn't seem to actually make a difference to me though. I tested it out by simply deleting the file. Chrome still can't set the default browser either way, so I don't think it matters? Perhaps the flatpak policy can just be removed for now?

**Comment by refi64** [comment]
The goal is mostly to avoid the button even being an option, so it's more of a "default browser setting is unsupported" vs "default browser setting is not working", the latter of which looks more like a bug.

**Comment by ludvigng** [comment]
Yeah that's fair, but I think it might also make users confused by what it means that their browser is "managed by an organization", when they haven't received any warning what that means.

It's a tough call, because as you said, the alternative would look like a bug.
