### ISSUE TITLE
Chrome can't access all the Home directories

### ISSUE THREAD

**Issue by daquinons** [flathub/com.google.Chrome#46]
- Go to any website that allows to upload (for example, https://imgur.com/upload and click on "Choose photo/video")
- See only "Documents", "Downloads", "Music" and "Video" in your Home directory

**Comment by Erick555** [comment]
This is intended, see https://github.com/flathub/com.google.Chrome/commit/c036ecbc3cea8d1b8ebee1c3cda8a158a0a19eed .

**Comment by daquinons** [comment]
Would be adding `--filesystem=xdg-pictures` accepted in a PR? I believe Pictures should be included by default if Videos folder is included.

**Comment by refi64** [comment]
I'd be okay with that personally, it would fit with what Discord has ootb iirc?
