### ISSUE TITLE
Does Chrome on Flatpak use encrypted keychain for passwords e.g. on Gnome?

### ISSUE THREAD

**Issue by Mershl** [flathub/com.google.Chrome#56]
Upstream Chrome / .deb/.rpm Chrome uses the Gnome keychain to save locally saved passwords encrypted with the current login. 

Does Chrome on Flatpak do the same / similar to protect locally saved/synced passwords?

**Comment by refi64** [comment]
It should be (you can check the password format in the database yourself to ensure this but I don't recall the commands off the top of my head).

**Comment by Mershl** [comment]
Just checked with Gnome Seahorse. Yep, they are encrypted using the same method (Chrome Safe Storage with secret) as non-flatpak Chrome.
