### ISSUE TITLE
Sort out "Add to desktop" side effects

### ISSUE THREAD

**Issue by refi64** [flathub/com.google.Chrome#81]
Right now, if `--filesystem=home` is enabled, checking "Add to desktop" when installing a PWA will create a broken shortcut on the desktop, or do nothing if the filesystem access isn't given.

**Comment by wjt** [comment]
More precisely, `/usr/bin/xdg-desktop-icon` (which I guess must be (transitively?) invoked by Chromium) saves the desktop icon to `xdg-desktop-dir DESKTOP`, which on most systems is `~/Desktop` (localized). My Endless OS system has this configured to `~`. Flathub Chromium has the same behaviour.

**Comment by wjt** [comment]
(I had previously wished for flatpak-xdg-utils to provide simplified versions of these tools: https://github.com/flatpak/flatpak-xdg-utils/issues/35)

**Comment by refi64** [comment]
This was fixed already.

**Comment by Mailaender** [comment]
How did you fix it?
